# Generated by Django 3.0.8 on 2020-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securities',
            name='roi',
            field=models.IntegerField(default=5, verbose_name='rate of int'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='tenure',
            field=models.IntegerField(default=1),
        ),
    ]
