# Generated by Django 3.0.8 on 2020-10-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0004_auto_20201016_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficary',
            name='ben_contact',
            field=models.EmailField(default='mydefault@email.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='securities',
            name='doxs',
            field=models.FileField(default='uploads_old/', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='beneficary',
            name='beneficary',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='instaddr',
            field=models.CharField(help_text='Enter City Name', max_length=100, unique=True, verbose_name='Institution Address'),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='instype',
            field=models.CharField(choices=[('BNK', 'Bank'), ('FNC', 'FinanceCompany'), ('INS', 'InsuranceComp')], max_length=30, verbose_name='Type of Intstitute'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='securities',
            name='tenure',
            field=models.IntegerField(default=1, verbose_name='Tenure in months'),
        ),
    ]
