# Generated by Django 3.0.8 on 2020-10-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0006_auto_20201019_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficary',
            old_name='ben_contact',
            new_name='benfcontact',
        ),
    ]
