# Generated by Django 3.0.8 on 2020-10-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0007_auto_20201019_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficary',
            name='beneficary',
            field=models.CharField(max_length=30),
        ),
    ]
