# Generated by Django 3.0.8 on 2020-10-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0008_auto_20201019_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficary',
            name='beneficary',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficary',
            name='benfcontact',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
