# Generated by Django 3.0.8 on 2020-10-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0010_auto_20201028_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficary',
            name='beneficary',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
