# Generated by Django 3.0.8 on 2020-11-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0012_auto_20201028_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficary',
            name='benfcontact',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
