# Generated by Django 3.0.8 on 2020-11-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0015_auto_20201122_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='instaddr',
            field=models.CharField(help_text='Enter City Name', max_length=100, verbose_name='Institution Address'),
        ),
    ]
