# Generated by Django 3.0.8 on 2020-11-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdms', '0016_auto_20201124_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securities',
            name='roi',
            field=models.FloatField(default=5.0, verbose_name='rate of int'),
        ),
    ]
