# Generated by Django 2.1.5 on 2019-01-22 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofholder', models.CharField(max_length=20, unique=True)),
                ('emailid', models.CharField(max_length=30, unique=True)),
                ('mobno', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='credntials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=24)),
                ('secq', models.CharField(default='whats my favorite color', max_length=60)),
                ('seca', models.CharField(default='yellow', max_length=20)),
                ('noh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credntials.AccHolder')),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofinst', models.CharField(default='new3', max_length=50, unique='True')),
            ],
        ),
        migrations.CreateModel(
            name='InstType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typins', models.CharField(default='new1', max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='institutions',
            name='typofins',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credntials.InstType'),
        ),
        migrations.AddField(
            model_name='credntials',
            name='noi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credntials.Institutions'),
        ),
        migrations.AddField(
            model_name='credntials',
            name='noit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credntials.InstType'),
        ),
    ]
