# Generated by Django 2.2.9 on 2020-02-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credntials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insttype',
            name='instname',
            field=models.CharField(default='new2', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='accholder',
            name='emailid',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='accholder',
            name='mobno',
            field=models.IntegerField(unique=True),
        ),
    ]
