# Generated by Django 2.2.9 on 2020-02-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credntials', '0002_auto_20200202_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insttype',
            name='instname',
        ),
    ]
